POST  http://localhost:3000/users
Content-Type: application/json

{
    "email": "olivier1@mail.com",
    "username":"oliver1",
    "password": "bestPassw0rd"
}

###

GET http://localhost:3000/users

