POST  http://localhost:3000/register
Content-Type: application/json

{
    "email": "olivier1@mail.com",
    "username":"oliver1",
    "password": "bestPassw0rd"
}
### Login
POST  http://localhost:3000/login
Content-Type: application/json

{
    "username":"oliver1",
    "password": "bestPassw0rd"
}


###

GET http://localhost:3000/products

###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY2ODA5MjAwNSwiZXhwIjoxNjY4MDkyOTA1fQ.7HeIOL-cdl4PMCdi_5tzwDwaMqHI1JKiCIAXlXuLpQU
###
POST  http://localhost:3000/login
Content-Type: application/json

{
    "username":"admin",
    "password": "admin"
}